# cargo-deny config - supply-chain checks (bans / sources).
# RustSec advisories are covered separately by `cargo audit` (rustsec/audit-check) in the
# security-audit workflow, so they are intentionally not duplicated here. Add a [licenses]
# allow-list and `licenses` to the workflow `command:` once the dependency tree is license-reviewed.
[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
